/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DemoStoreRouteImport } from './routes/demo.store'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo.tanstack-query'
import { Route as MatchesIndexRouteImport } from './routes/matches.index'
import { Route as WatchIndexRouteImport } from './routes/watch.index'
import { Route as WatchMatchIdRouteImport } from './routes/watch.$matchId'
import { Route as MatchesMatchIdReplayRouteImport } from './routes/matches.$matchId.replay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIndexRoute = WatchIndexRouteImport.update({
  id: '/watch/',
  path: '/watch/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchMatchIdRoute = WatchMatchIdRouteImport.update({
  id: '/watch/$matchId',
  path: '/watch/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdReplayRoute = MatchesMatchIdReplayRouteImport.update({
  id: '/matches/$matchId/replay',
  path: '/matches/$matchId/replay',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/watch/$matchId': typeof WatchMatchIdRoute
  '/matches/': typeof MatchesIndexRoute
  '/watch/': typeof WatchIndexRoute
  '/matches/$matchId/replay': typeof MatchesMatchIdReplayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/watch/$matchId': typeof WatchMatchIdRoute
  '/matches': typeof MatchesIndexRoute
  '/watch': typeof WatchIndexRoute
  '/matches/$matchId/replay': typeof MatchesMatchIdReplayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/watch/$matchId': typeof WatchMatchIdRoute
  '/matches/': typeof MatchesIndexRoute
  '/watch/': typeof WatchIndexRoute
  '/matches/$matchId/replay': typeof MatchesMatchIdReplayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/watch/$matchId'
    | '/matches/'
    | '/watch/'
    | '/matches/$matchId/replay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/watch/$matchId'
    | '/matches'
    | '/watch'
    | '/matches/$matchId/replay'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/watch/$matchId'
    | '/matches/'
    | '/watch/'
    | '/matches/$matchId/replay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  WatchMatchIdRoute: typeof WatchMatchIdRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
  WatchIndexRoute: typeof WatchIndexRoute
  MatchesMatchIdReplayRoute: typeof MatchesMatchIdReplayRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/': {
      id: '/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/': {
      id: '/watch/'
      path: '/watch'
      fullPath: '/watch/'
      preLoaderRoute: typeof WatchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$matchId': {
      id: '/watch/$matchId'
      path: '/watch/$matchId'
      fullPath: '/watch/$matchId'
      preLoaderRoute: typeof WatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId/replay': {
      id: '/matches/$matchId/replay'
      path: '/matches/$matchId/replay'
      fullPath: '/matches/$matchId/replay'
      preLoaderRoute: typeof MatchesMatchIdReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  WatchMatchIdRoute: WatchMatchIdRoute,
  MatchesIndexRoute: MatchesIndexRoute,
  WatchIndexRoute: WatchIndexRoute,
  MatchesMatchIdReplayRoute: MatchesMatchIdReplayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
